baseURL: "https://ujwalkandi.in/"
title: Ujwal Kandi
paginate: 5
remote_theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-M6PE73SR22


title: < Home >
profileMode:
    enabled: true
    title: Ujwal Kandi


        
menu:
    main:
        - name: About
          url: https://ujwalkandi.in/about/
          weight: 5
        - name: Projects
          url: https://ujwalkandi.in/projects/
          weight: 5
        - name: Portfolio
          url: https://ujwalkandi.in/portfolio/ 
          weight: 5
        - name: Links
          url: https://ujwalkandi.in/links/
          weight: 5
        - name: Resume
          url: https://ujwalkandi.in/assets/Ujwal_Kandi_Resume.pdf
          weight: 10
                 

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Personal Website/Blog of Ujwal Kandi"
    author: Ujwal Kandi

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true



    homeInfoParams:
        Title: "Ujwal Kandi"
        Content: >
            A Data Programmer and Developer with interests in Data Science, Finance, Cloud and Programming; loves Open-Source & Data Visualization.
            - Data Programmer @ [Epsilon](https://www.epsilon.com/).
            - Fellow @ [University Innovation Fellows](https://universityinnovationfellows.org/).
            

    socialIcons:
        - name: github
          url: "https://ujwalkandi.in/links"
        - name: RsS
          url: "index.xml"



    assets:
        favicon: "https://ujwalkandi.in/assets/img/favicon.ico"
        favicon16x16: "https://ujwalkandi.in/assets/img/favicon-16x16.png"
        favicon32x32: "https://ujwalkandi.in/assets/img/favicon-32x32.png"
        apple_touch_icon: "https://ujwalkandi.in/assets/img/apple-touch-icon.png"
        safari_pinned_tab: "https://ujwalkandi.in/assets/img/android-chrome-512x512.png"


markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
